### PR TITLE
ci: Publish to crates.io.

### PR DESCRIPTION
**Pull request by dewyatt**
I've only tested the dry-run of this, so it may or may not work correctly.
@ronaldtse Can you add the `CARGO_REGISTRY_TOKEN` for crates.io?

### CODE REVIEW

**Comment by ronaldtse** [comment]
@dewyatt added! This token is from the "rnp-ci" account, I wasn't sure if enprot will end up closer to rnp or metanorma, or a completely separate beast... (suggestions welcome!)

**Comment by ronaldtse** [comment]
While we're at this, what's your view on using GitHub Actions like this? https://github.com/actions-rs/cargo

**Comment by dewyatt** [comment]
> While we're at this, what's your view on using GitHub Actions like this? https://github.com/actions-rs/cargo

I thought about it, but it really doesn't seem all that useful unless I'm missing something.

**Comment by ronaldtse** [comment]
That's true, it's more like a wrapper. Feel free to merge if ready.

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
